In [1]:
import numpy as np
import re
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split # 分割数据模块

In [2]:
with open('faceDR','r') as f:
    for line in f.readlines():
        print(line)

 1223 (_sex  male) (_age  child) (_race white) (_face smiling) (_prop '())

 1224 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1225 (_sex  male) (_age  child) (_race white) (_face smiling) (_prop '())

 1226 (_sex  male) (_age  child) (_race white) (_face smiling) (_prop '())

 1227 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1228 (_missing descriptor)

 1229 (_sex  male) (_age  adult) (_race white) (_face serious) (_prop '())

 1230 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1231 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1232 (_missing descriptor)

 1233 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1234 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1235 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1236 (_sex  male) (_age  child) (_race white) (_face serious) (_prop '())

 1237 (_sex  male) (_age  chil

In [12]:
label = []
num_delete = []
num = np.zeros([4,5])    #记录每个特征数量
with open('faceDR','r') as f:
    for line in f.readlines():
        m = re.findall(r' (\w+)',line) 
        if len(m) >2:
            m = m[0:5]
            m[0] = int(m[0])
            #判断性别
            if m[1] == 'female':
                m[1]= 0
                num[0][0] = num[0][0]+1
            elif m[1] == 'male':
                m[1] = 1
                num[0][1] = num[0][1]+1
            #判断年龄
            if m[2] == 'child':
                m[2]= 0
                num[1][0] = num[1][0]+1
            elif m[2] == 'teen':
                m[2] = 1
                num[1][1] = num[1][1]+1
            elif m[2] == 'adult':
                m[2] = 2
                num[1][2] = num[1][2]+1
            elif m[2] == 'senior':
                m[2] = 3
                num[1][3] = num[1][3]+1
            #判断肤色
            if m[3] == 'white':
                m[3]= 0
                num[2][0] = num[2][0]+1
            elif m[3] == 'black':
                m[3] = 1
                num[2][1] = num[2][1]+1
            elif m[3] == 'hispanic':
                m[3] = 2
                num[2][2] = num[2][2]+1
            elif m[3] == 'asian':
                m[3] = 3
                num[2][3] = num[2][3]+1
            elif m[3] == 'other':
                m[3] = 4
                num[2][4] = num[2][4]+1
            #判断表情    
            if m[4] == 'smiling':
                m[4]= 0
                num[3][0] = num[3][0]+1
            elif m[4] == 'funny':
                m[4] = 1
                num[3][1] = num[3][1]+1
            elif m[4] == 'serious':
                m[4] = 2
                num[3][2] = num[3][2]+1
            
            label.append(m)
        else :
            num_delete.append(int(m[0]))

In [13]:
num

array([[ 847., 1150.,    0.,    0.,    0.],
       [ 244.,  261., 1438.,   54.,    0.],
       [1840.,   64.,   26.,   55.,   12.],
       [1043.,   37.,  917.,    0.,    0.]])

In [14]:
label

[[1223, 1, 0, 0, 0],
 [1224, 1, 0, 0, 2],
 [1225, 1, 0, 0, 0],
 [1226, 1, 0, 0, 0],
 [1227, 1, 0, 0, 2],
 [1229, 1, 2, 0, 2],
 [1230, 1, 0, 0, 2],
 [1231, 1, 0, 0, 2],
 [1233, 1, 0, 0, 2],
 [1234, 1, 0, 0, 2],
 [1235, 1, 0, 0, 2],
 [1236, 1, 0, 0, 2],
 [1237, 1, 0, 0, 2],
 [1238, 1, 0, 0, 2],
 [1239, 1, 0, 0, 2],
 [1240, 1, 0, 0, 2],
 [1241, 1, 0, 0, 2],
 [1242, 1, 0, 0, 2],
 [1243, 1, 0, 0, 2],
 [1244, 1, 0, 0, 2],
 [1245, 1, 0, 0, 2],
 [1246, 1, 0, 0, 2],
 [1247, 1, 0, 0, 2],
 [1248, 1, 0, 0, 2],
 [1249, 1, 0, 0, 1],
 [1250, 1, 0, 0, 2],
 [1251, 1, 0, 0, 2],
 [1252, 0, 0, 0, 0],
 [1253, 1, 0, 0, 2],
 [1254, 1, 0, 0, 2],
 [1255, 1, 0, 0, 2],
 [1256, 0, 0, 0, 2],
 [1257, 0, 0, 0, 2],
 [1258, 1, 0, 0, 0],
 [1259, 1, 0, 0, 0],
 [1260, 1, 0, 0, 0],
 [1261, 1, 0, 0, 0],
 [1262, 0, 0, 0, 0],
 [1263, 1, 0, 0, 0],
 [1264, 1, 0, 0, 0],
 [1265, 1, 0, 0, 0],
 [1266, 1, 0, 0, 0],
 [1267, 1, 0, 0, 2],
 [1268, 1, 0, 0, 0],
 [1269, 1, 1, 0, 2],
 [1270, 1, 1, 0, 2],
 [1271, 1, 0, 0, 0],
 [1272, 1, 0,

In [15]:
import pandas as pd

In [16]:
num_delete

[1228, 1232, 1808]

In [17]:
data = pd.read_csv('faceR',header =None,sep='\s+' ,engine = 'python')

In [27]:
data[0:10]

0            1            2           3            4            5   \
0   1223 -1779.619019  2107.301270  807.759949  -654.226135   322.416931   
1   1224 -2719.973389  2978.843750  -12.276579  -146.023010  1998.795898   
2   1225  -946.141785 -1171.160278  557.305603 -1194.493408  -216.099808   
3   1226   923.962097    -3.056940  824.880981  -885.380859   570.907410   
4   1227  1747.073242  1018.751465  818.763611  -725.350769   479.929474   
6   1229 -1522.900513    36.874554  935.710999  -495.797668   962.575928   
7   1230 -4058.238525   635.122925  896.540710 -1881.652832    39.938805   
8   1231   385.005646    -2.431623  911.578247 -2325.569336  -321.058044   
10  1233  -310.221588  2732.313721  110.604103  -334.133209  1139.488892   
11  1234   250.836563  1529.763794  812.376526  -208.554047   903.943909   

             6           7            8           9   ...          90  \
0   1075.673706  559.180786   452.465454 -561.820374  ...  117.541168   
1   1465.912964 -365.699615   918.354187  280.471558  ...  279.086487   
2  -1391.826782 -485.291290  -464.110687  117.395042  ...    8.953163   
3    391.960388  171.401001  -315.220154  417.925110  ...   72.076035   
4    103.267044 -280.265503   632.580872  639.264648  ...  -15.325751   
6    130.490677 -227.445862  -171.987701  301.244995  ...  -62.699722   
7   -541.397522 -956.085327  -950.445496  753.252930  ...   58.788624   
8    126.941460 -513.124329 -1044.275635  363.835052  ...  115.792839   
10   358.553467 -178.268311   558.735962   78.052383  ...  106.646866   
11  1381.364380   71.628487   -50.475998  792.716309  ...  -14.674956   

            91          92          93          94          95          96  \
0   -12.968436  253.902130 -180.755005  120.390350  207.105194  144.583420   
1    76.618538  130.531647   53.132874  -51.564190  138.686768  -46.186413   
2   -87.083122  149.273239  149.089874  -27.231977  164.404236  -35.551216   
3  -106.367004  124.044701   64.637459  124.859024 -160.011261 -193.557053   
4   -86.639343   77.209099  -41.741447  127.171127  -49.919292  -47.129459   
6    93.288986    3.170109  -16.972132 -107.151344  180.052429 -123.944084   
7  -292.081696   61.732021    8.974833  200.831177  108.465324   -2.809121   
8   -13.036229   40.183453   55.053616  -18.036270  122.410049   47.397587   
10  126.898682  -71.222153    3.242263   57.633347   50.887150  -43.744484   
11 -135.852844   81.035675   55.398079 -116.861832  -91.054871  -58.390282   

            97          98          99  
0   -86.194237   12.877232   23.882339  
1    -4.687377  -42.803467   11.986197  
2    60.023273    2.219028   16.627527  
3   -35.120018  -60.099522   30.020988  
4   -24.203516  -70.808853   -3.180266  
6   178.897812 -108.937302   68.118324  
7     6.312848 -178.880051 -110.021477  
8   -29.621273   69.082977   47.114536  
10  -13.893540  159.378311   51.482277  
11   15.263933   19.124689   31.849098  

[10 rows x 100 columns]

In [19]:
#删除无效数据
idx =[]
for i in num_delete:
    idx.append(np.where(data[0] == i)[0][0])
   # print(idx)
data = data.drop(idx)

In [23]:
x = data.iloc[:,1:].values.astype('float32')
#x = preprocessing.normalize(x, norm='l2')
x.shape

(1997, 99)

In [24]:
label = np.array(label)
y = label[:,1]
y.shape

(1997,)

In [25]:
x

array([[-1.7796190e+03,  2.1073013e+03,  8.0775995e+02, ...,
        -8.6194237e+01,  1.2877232e+01,  2.3882339e+01],
       [-2.7199734e+03,  2.9788438e+03, -1.2276579e+01, ...,
        -4.6873770e+00, -4.2803467e+01,  1.1986197e+01],
       [-9.4614178e+02, -1.1711603e+03,  5.5730560e+02, ...,
         6.0023273e+01,  2.2190280e+00,  1.6627527e+01],
       ...,
       [ 1.0773677e+03, -6.2496265e+02, -4.6885779e+02, ...,
         3.0873987e+01, -1.7644610e+00,  6.3269218e+01],
       [ 1.6275127e+02,  1.9290243e+03, -3.1021328e+03, ...,
         1.2896179e+02,  5.9127243e+01, -5.7387140e+02],
       [-6.9770898e+02, -2.3646791e+01,  1.3313634e+03, ...,
        -9.6887627e+01, -1.0557869e+02,  1.0343335e+02]], dtype=float32)

In [14]:
#保存数据
np.save('test_data',x)
np.save('test_label',label)

In [1]:
import scipy.io as scio
# 读取matlab文件特征向量
d = scio.loadmat('ev.mat')

In [3]:
d

{'mean_face': array([[0., 0., 0., ..., 0., 0., 0.]]),
 'eigenfaces': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'ev100': array([[0., 0., 0., ..., 0., 0., 0.]])}

In [4]:
d['mean_face']

array([[0., 0., 0., ..., 0., 0., 0.]])

In [12]:
#knn
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=2)
#建立模型
knn = KNeighborsClassifier()
#训练模型
knn.fit(X_train, y_train)
#将准确率打印出
print(knn.score(X_test, y_test))

0.718


In [13]:
#支持向量机
clf1 = SVC(kernel='linear')
clf1.fit(x,y)
y_pred = clf1.predict(X_test)
miss_classified = (y_pred != y_test).sum()
print("MissClassified: ",miss_classified)

MissClassified:  92
